import { motion } from "framer-motion";

export default function AboutUs() {
  return (
    <section className="bg-gray-50 text-gray-800 py-20 px-6 md:px-12 lg:px-24">
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <h2 className="text-4xl md:text-5xl font-bold mb-4 tracking-tight">
            About <span className="text-blue-600">Vitae</span>
          </h2>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Vitae is more than just a resume builder — it’s my story turned into
            a tool for everyone. Built with passion, code, and the belief that
            opportunities should be accessible to all.
          </p>
        </motion.div>

        {/* Story Section */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
          {/* Left: Image */}
          <motion.div
            initial={{ opacity: 0, x: -60 }}
            whileInView={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.7 }}
            viewport={{ once: true }}
            className="relative"
          >
            <img
              src="https://images.unsplash.com/photo-1519389950473-47ba0277781c"
              alt="Coding and building Vitae"
              className="rounded-2xl shadow-xl object-cover w-full h-[350px]"
            />
            <div className="absolute -bottom-6 -left-6 bg-blue-600 text-white px-6 py-4 rounded-xl shadow-xl">
              <h3 className="text-xl font-semibold">Built with MERN</h3>
              <p className="text-sm">From the Philippines, for the world</p>
            </div>
          </motion.div>

          {/* Right: Text */}
          <motion.div
            initial={{ opacity: 0, x: 60 }}
            whileInView={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.7 }}
            viewport={{ once: true }}
          >
            <h3 className="text-2xl md:text-3xl font-semibold mb-4">
              The Story Behind Vitae
            </h3>
            <p className="text-gray-600 mb-6 leading-relaxed">
              I’m <span className="font-medium">Christian Moises</span>, a fresh
              computer science graduate from the Philippines. Like many others,
              I faced the challenge of building a strong resume without paying
              for overpriced tools. Instead of settling, I decided to build my
              own solution — and that’s how Vitae was born.
            </p>
            <p className="text-gray-600 leading-relaxed">
              Vitae is not just my project; it’s my mission: to help graduates
              and job seekers craft polished resumes, refine them with AI, and
              connect with real job opportunities  all for free.
            </p>
          </motion.div>
        </div>

        {/* Mission Statement */}
        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          transition={{ duration: 0.8, delay: 0.3 }}
          viewport={{ once: true }}
          className="mt-20 bg-white rounded-2xl shadow-md p-10 text-center"
        >
          <h3 className="text-2xl md:text-3xl font-bold mb-4">Our Mission</h3>
          <p className="text-gray-600 max-w-3xl mx-auto leading-relaxed">
            Vitae was built with one goal: to level the playing field. Whether
            you’re a fresh graduate or a seasoned professional, you deserve a
            resume that reflects your potential  without financial barriers.
            With AI-powered revision, smart templates, and job matching, Vitae
            helps you take the next step in your career with confidence. btw. this about us page is completely generated by AI. hahahaha crazy right?
          </p>
        </motion.div>
      </div>
    </section>
  );
}
